# https://stackoverflow.com/questions/65698145/kivymd-tab-name-containing-icons-and-text
# this import will prevent disappear tabs through some clicks on them)))
#:import md_icons kivymd.icon_definitions.md_icons
#:import fonts kivymd.font_definitions.fonts

# https://github.com/tito/kivy-gettext-example
# this import for multilingual support
#:import tr __main__.tr

MDScreen:
    name:"credit"
    BoxLayout:
        padding: "10dp"
        MDLable:
            text:"SecondScreen"
